member = dict(秋元真夏='manatsu.akimoto',
               生田絵梨花='erika.ikuta',
               生駒里奈='rina.ikoma',
               伊藤かりん='karin.itou',
               伊藤純奈='junna.itou',
               伊藤理々杏='riria.itou',
               井上小百合='sayuri.inoue',
               岩本蓮加='renka.iwamoto',
               梅澤美波='minami.umezawa',
               衛藤美彩='misa.eto',
               大園桃子='momoko.oozokno',
               川後陽菜='hina.kawago',
               北野日奈子='hinako.kitano',
               久保史緒里='shiori.kubo',
               齋藤飛鳥='asuka.saito',
               斎藤ちはる='chiharu.saito',
               斉藤優里='yuuri.saito',
               阪口珠美='tamami.sagaguchi',
               相楽伊織='iori.sagara',
               桜井玲香='reika.sakurai',
               佐々木琴子='kotoko.sasaki',
               佐藤楓='kaede.satou',
               白石麻衣='mai.shiraishi',
               新内眞衣='mai.shinuchi',
               鈴木絢音='ayane.suzuki',
               高山一実='kazumi.takayama',
               寺田蘭世='ranze.terada',
               中田花奈='kana.nakada',
               中村麗乃='reno.namamura',
               西野七瀬='nanase.nishino',
               能條愛未='ami.noujo',
               樋口日奈='hina.higuchi',
               星野みなみ='minami.hoshino',
               堀未央奈='miona.hori',
               松村沙友理='sayuri.matsumura',
               向井葉月='hazuki.mukai',
               山﨑怜奈='rena.yamazaki',
               山下美月='mizuki.yamashita',
               吉田綾乃クリスティー='ayanochristie.yoshida',
               与田祐希='yuuki.yoda',
               若月佑美='yumi.wakatsuki',
               渡辺みり愛='miria.watanabe',
               和田まあや='maaya.wada')

headers = {'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
'Accept-Encoding': 'gzip, deflate',
'Accept-Language': 'ja,en-US;q=0.9,en;q=0.8',
'Connection': 'keep-alive',
'Host': 'blog.nogizaka46.com',
'Upgrade-Insecure-Requests': '1',
'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'}
